changelog:
  exclude:
    labels:
      - duplicate
      - question
      - wontfix
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 📖 Documentation
      labels:
        - documentation
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - '*'