name: "Setup pnpm"
description: "Install node and pnpm"

runs:
  using: "composite"
  steps:
    - name: "Setup pnpm"
      uses: pnpm/action-setup@v4
      id: pnpm-install
      with:
        version: 10
        run_install: false

    - name: "Setup Node"
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "pnpm"
