name: 'Build SvelteKit app'
on:
  workflow_call: {}

jobs:
  build:
    name: 'Build the-easy-link'
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v4

      - name: 'Setup pnpm'
        uses: ./.github/actions/setup-pnpm

      - name: 'Replace env variables'
        uses: danielr1996/envsubst-action@1.1.0
        env:
          FIREBASE_API_KEY: ${{ vars.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ vars.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ vars.FIREBASE_MEASUREMENT_ID }}
        with:
          input: .env.ci
          output: .env

      - name: 'Install dependencies'
        run: pnpm install

      - name: 'Build app'
        run: pnpm build

      - name: 'Upload build artifact'
        uses: actions/upload-artifact@v4
        with:
          name: 'build'
          path: './public'
