name: 'Deploy to Firebase Hosting'
on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build'
    uses: ./.github/workflows/build-sveltekit.yml

  deploy:
    name: 'Deploy to Firebase'
    runs-on: ubuntu-latest
    needs: build
    outputs:
      url: ${{ steps.firebase-deploy.outputs.details_url }}
    steps:
      - uses: actions/checkout@v4

      - name: 'Download build artifact'
        uses: actions/download-artifact@v4
        with:
          name: 'build'
          path: './public'

      - name: 'Deploy to Firebase Hosting'
        id: firebase-deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: the-easy-link
          channelId: live
