name: 'Deploy Firebase Services'
on:
  push:
    tags:
      - 'v*.*.*'

env:
  PROJECT_ID: the-easy-link

jobs:
  validate:
    name: 'Validate version'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: 'Get tag version'
        id: version
        run: |
          tag=$(echo ${{ github.ref_name }})
          echo "version=${tag#v}" >> $GITHUB_OUTPUT

      - name: 'Check app version'
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          PKG_VERSION=$(jq -r '.version' package.json)
          if [ "$VERSION" != "$PKG_VERSION" ]; then
            echo "The version '$VERSION' does not match the version defined in the package.json file. Please update the version in the package.json file."
            echo "⛔ The version \`$VERSION\` does not match the version defined in the package.json file. Please update the version in the package.json file." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: 'Check CHANGELOG.md'
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          if ! grep -q "^## \[$VERSION\]" CHANGELOG.md; then
            echo "The version '$VERSION' is not present in the CHANGELOG.md file. Please document the changes."
            echo "⛔ The version \`$VERSION\` is not present in the \`CHANGELOG.md\` file. Please document the changes." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

  build:
    name: 'Build app'
    needs: validate
    uses: ./.github/workflows/build-sveltekit.yml

  hosting:
    name: 'Deploy Hosting'
    runs-on: ubuntu-latest
    needs: build
    outputs:
      url: ${{ steps.firebase-deploy.outputs.details_url }}
    steps:
      - uses: actions/checkout@v4

      - name: 'Download build artifact'
        uses: actions/download-artifact@v6
        with:
          name: 'build'
          path: './public'

      - name: 'Deploy to Firebase Hosting'
        id: firebase-deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ env.PROJECT_ID }}
          channelId: live

  firestore:
    name: 'Deploy Firestore'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            firebase.json
            firestore.rules
            firestore.indexes.json

      - name: 'Install Firebase CLI'
        run: npm install -g firebase-tools
        shell: bash

      - name: 'Authenticate Firebase CLI'
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      - name: 'Deploy Security Rules'
        run: firebase deploy --only firestore:rules --non-interactive --project ${{ env.PROJECT_ID }}

  release:
    name: 'GitHub release'
    needs: hosting
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: 'Create release'
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create "${{ github.ref_name }}" --title "${{ github.ref_name }}" --generate-notes
